### ISSUE TITLE
[BUG]Un-handeled rejecetion error for chat.

### ISSUE THREAD

**Issue by bobthedev90368** [noblox/noblox.js#470]
I am pretty sure this is a bug :)
 I have a bot that adds a user to a new group chat once they send a friend request. The error i get is:

Unhandled rejection Error: Send chat message failed
    at C:\Users\Admin\Code\Discord\node_modules\noblox.js\lib\chat\sendChatMessage.js:45:15
    at tryCatcher (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Admin\Code\Discord\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

Part of my code which I believe I am getting the error from is:

            if (sendmessage1) {
                conversationid = noblox.startGroupConversation([data, data], "#### Bot");
                conversations.push(conversationid);
                console.log(conversations);
                console.log(conversationid);
                setTimeout(function() { noblox.sendChatMessage(conversationid, "Hello, I am #### how may I help you?"); }, 1000);
                sendmessage1 = false;
            }

the users is already a friend.
The user id is passed through the data variable.
Sendmessage1 is set o true at beginning of run.
Conversation is a text file and I removed it without fixing the errors.
Noblox is well noblox.

Correct me if I'm wrong, but I think it is an internal error.
Thank you for your time!

*Edit*
The hashes are not actually in the code. They release info I am not yet ready to release.

**Comment by alanbixby** [comment]
`conversationid` would be an [unresolved promise](https://noblox.js.org/tutorial-Promises.html), thus triggering the error in `sendChatMessage()`.

Also make sure you have sufficient permissions between both accounts to initiate a group conversation.

**Comment by bobthedev90368** [comment]
Thank you!
