### ISSUE TITLE
[BUG] buy(), getProductInfo() errors everytime when used

### ISSUE THREAD

**Issue by Crazyblox** [noblox/noblox.js#679]
**EDIT: A NEW ALTERNATIVE ENDPOINT TO RESOLVE BUG AS EXPLAINED BELOW:**
https://economy.roblox.com/v2/assets/ASSETIDHERE/details

**Describe the bug**
Global method buy(asset, price opt) errors everytime when used, citing:
HTTP Error 410: The page you requested was removed.

The stack track goes back to the getProductInfo() method, on line 43 which contains a request for (https://api.roblox.com/marketplace/productinfo), which when accessed via any browser returns the same error.

This leads me to believe that roblox has removed the endpoint, and now noblox.js needs to be updated to reflect this change. Personally hoping that roblox hasn't shut down all endpoints related to this and that there is still an alternative available.

**To Reproduce**
Log in via noblox.js and use the buy() method on any purchasable asset on roblox.

**Expected behavior**
A purchase request should be made successfully.

**Additional context**
Error: 410 The page you requested was removed.
    at C:\Users\Crazyblox\node_modules\noblox.js\lib\asset\getProductInfo.js:43:20
    at tryCatcher (C:\Users\Crazyblox\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Crazyblox\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Crazyblox\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Crazyblox\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Crazyblox\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Crazyblox\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Crazyblox\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Crazyblox\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\Crazyblox\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)

**Comment by verbxtim** [comment]
Also having this issue.

**Comment by suufi** [comment]
Has been fixed. Please update to v4.14.0.
