### ISSUE TITLE
[BUG] Error when uploading item

### ISSUE THREAD

**Issue by nottisa** [noblox/noblox.js#681]
```const noblox = require("noblox.js");
const fs = require("fs");

noblox.setCookie().then(function() { //Use COOKIE from our .env file.
    console.log("Logged in!")
}).catch(function(err) {
    console.log("Unable to log in!", err)
})


async function bob() {
    await noblox.uploadItem("test", 13, fs.createReadStream("./mage.png"))
}
bob()
```
**Expected behavior**
It should upload the image as a decal....

**Error**
I get this error: 
```/workspaces/plsdonatestuff/node_modules/noblox.js/lib/asset/uploadItem.js:64
              reject(new Error('Unknown redirect: ' + location))
                     ^

Error: Unknown redirect: https://www.roblox.com/request-error?id=a654406b-ff4d-450a-bad3-d64a433a22c9&mode=&code=500
    at /workspaces/plsdonatestuff/node_modules/noblox.js/lib/asset/uploadItem.js:64:22
    at tryCatcher (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/workspaces/plsdonatestuff/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:475:21)```

**Comment by Neztore** [comment]
Could you look into this further? Has the API changed? have you managed to work around it?

**Comment by nottisa** [comment]
I could, but at the moment I'm a bit lazy, I will probably come back to this project in a couple months...

**Comment by Neztore** [comment]
We will deprecate this method and add the same functionality using open cloud
