### ISSUE TITLE
[BUG] noblox.getConversations returns not logged in error

### ISSUE THREAD

**Issue by nottisa** [noblox/noblox.js#753]
The noblox.getConversations function call throws a not logged in error even though noblox is logged in successfully. Removing this line removes the error. 
```
console.log(await noblox.getConversations([conversationid])) // This line errors
await noblox.declineFriendRequest(data) // This line does not
```
Error:
```
Logged in as IAMAI_Bot [4589598455]
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: You are not logged in
    at E:\\Desktop\accountgen\RoRate\node_modules\noblox.js\lib\chat\getConversations.js:31:13
    at tryCatcher (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\\Desktop\accountgen\RoRate\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
PS E:\\Desktop\accountgen\RoRate>

**Comment by Neztore** [comment]
@nottisa It is maintained as much as we can, but we're all busy and not really using Roblox ourselves these days.
Please feel free to open a PR to fix, or get in touch if you'd like to help maintain.

**Comment by nottisa** [comment]
@Neztore I get it, I've mostly left the platform myself, I'll think about maintaining this, but to be honest, I've said I would maintain so many other projects...

**Comment by Neztore** [comment]
If you decide you're interested in helping out, we can discuss further in [discord](https://discord.gg/7UxWqYpK). Would be good to have a few contributors on board to help. Cheers
